### PR TITLE
New screen to split packs of products

### PR DESCRIPTION
**Pull request by Hedydd**
Packs of products such as a box of mars bars can unpacked into a quantity of another product.for example a number of single mars bars.

This will simplify stock movement and operations because a box of a product can be scanned and tracked by location or added from a delivery but then individual items will be unpacked at the point of sale.

### CODE REVIEW

**Comment by Hedydd** [comment]
This is now complete and ready to be pulled into the main product

**Comment by cubanflyer** [comment]
Hi John

I see that some of the trolls are coming out on the forum, I would love 
to reply myself to a couple of the posts, but I am not allowed to post 
on that forum. However according to Jack I am, strange!, especially when 
it tells me I am not allowed if I try to post.

It looks like you are starting to get the same kind of responses that I 
got, when I questioned why some of my posts had be removed for the 
Kitchen Screen I created as a support project to Unicenta. Then I found 
I could no longer post and they blamed it on Sourceforge or another 
admin removing my permissions whilst he was on holiday (there are only 2 
admins), but a friend could post. As part of my support I had a number 
of private Bitbucket repos, to which I had granted Jack access to, but 
as the code (3.70) was old I removed it as part of a tidy up process, 
and I was then accused of being vindictive.

I spent an awful amount time supporting the project and adding features 
only to find that I had to do it all again with each release.

If it was not for the support and encouragement of a few of the forum 
members, I think I would dropped everything, and not gone any further 
and created my own fork of the project. I would have preferred to 
continue contributing to the main project, and not created work for 
myself.

I consider any addition to the core project that will be of benefit to 
the users to be welcome, and I intend to keep it that way.

So any work you do is welcome from my point of view.



Regards
John

**Comment by Hedydd** [comment]
Hi John –they have made their choices, so have we, we must all make the most of things now. 

 

We need to keep monitoring those forums for bug reports and fixes that apply to Chromis as well. If we concentrate on making Chromis as good as we can, I am sure that over time it will become the de-facto free and Open Source POS, just as UnicentaPOS has been up till now. For me, it needs to have a good long term future as I have a business that will be heavily invested in using it.

 

John

**Comment by cubanflyer** [comment]
Hi John

I am having problems with Github and merging, I may have setup something 
wrong, so I might have to start again. I will let you know.

I have some changes ready for release and are with some beta testers. I 
am going to give you dev access on the forum, that means you can get at 
the beta release if you wish.

The biggest issue is catching all the exception errors in the convert 
routine, there is no accounting for what users do to the resource files.

Regards
John



On 17/09/2015 14:45, John Barrett wrote:
> Hi John –they have made their choices, so have we, we must all make 
> the most of things now.
>
>
>
> We need to keep monitoring those forums for bug reports and fixes that 
> apply to Chromis as well. If we concentrate on making Chromis as good 
> as we can, I am sure that over time it will become the de-facto free 
> and Open Source POS, just as UnicentaPOS has been up till now. For me, 
> it needs to have a good long term future as I have a business that 
> will be heavily invested in using it.
>
>
>
> John
>
>
>
>
>
> From: John Lewis [mailto:notifications@github.com]
> Sent: 16 September 2015 16:37
> To: ChromisPos/ChromisPOS
> Cc: John Barrett
> Subject: Re: [ChromisPOS] New screen to split packs of products (#6)
>
>
>
> Hi John
>
> I see that some of the trolls are coming out on the forum, I would love
> to reply myself to a couple of the posts, but I am not allowed to post
> on that forum. However according to Jack I am, strange!, especially when
> it tells me I am not allowed if I try to post.
>
> It looks like you are starting to get the same kind of responses that I
> got, when I questioned why some of my posts had be removed for the
> Kitchen Screen I created as a support project to Unicenta. Then I found
> I could no longer post and they blamed it on Sourceforge or another
> admin removing my permissions whilst he was on holiday (there are only 2
> admins), but a friend could post. As part of my support I had a number
> of private Bitbucket repos, to which I had granted Jack access to, but
> as the code (3.70) was old I removed it as part of a tidy up process,
> and I was then accused of being vindictive.
>
> I spent an awful amount time supporting the project and adding features
> only to find that I had to do it all again with each release.
>
> If it was not for the support and encouragement of a few of the forum
> members, I think I would dropped everything, and not gone any further
> and created my own fork of the project. I would have preferred to
> continue contributing to the main project, and not created work for
> myself.
>
> I consider any addition to the core project that will be of benefit to
> the users to be welcome, and I intend to keep it that way.
>
> So any work you do is welcome from my point of view.
>
>
>
> Regards
> John
>
>
>
>
>
>
>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ChromisPos/ChromisPOS/pull/6#issuecomment-140779903> 
> . 
> <https://github.com/notifications/beacon/AKeQDrhgH9NfaBbvuRZfmNWcjePq7BuCks5oyYQEgaJpZM4F8cZK.gif> 
>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ChromisPos/ChromisPOS/pull/6#issuecomment-141091303>.
>



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by Hedydd** [comment]
Hi John 

 

Where is the beta and your changes? Are they on your personal fork on GitHub? If so:

 

go to the last commit that you have on yourusername/ChromisPOS and create a Pull request for it.

 

Next Go to ChromisPOS/ChromisPOS and you should see the pull request there. Open the pull request and at the bottom you will see the option to merge that pull request into the master branch.

 

Finally create a new TAG to tag the release. If you need to re-release then you can create a new branch from this TAG to apply bugfixes without getting future developments into the re-release.

 

Once you are happy, you could then merge in the pull requests I have made to get my changes into the next release.

 

Finally we can both re-base our forks to the new ChromisPOS/ChromisPOS master to continue independant development.

 

John

**Comment by Hedydd** [comment]
These changes have now been done on a branch off ChromisPOS/ChromisPOS/master and a new pull request generated there. This pull request is now obsolete

**Pull request closed without merging**
