### PR TITLE
Bug fixes and new features to support a new set of features for The Corner Shop

### PR DESCRIPTION
**Pull request by Hedydd**
There is an old saying "blue and green should never be seen" The png icon files have been run through an auto conversion program to make them black and white.

This fork will also contain bug fixes and new features that can be pull back into the ChromisPOS/head as and when required

### CODE REVIEW

**Comment by cubanflyer** [comment]
Hi John 

I am going to merge the bug fixes, but I want to hold back on features for a short while I stabilize the project, and then I will add then in.

John

**Comment by Hedydd** [comment]
That sounds a sensible idea – I would seriously consider adopting the black icons colour scheme though – The green will be a little too much for many people and will put them off, black will be less contentious.

 

I will not let you know every time I commit changes because this will be almost daily for a while, I suggest you look at my fork from time to time to check for bug fixes.

 

John

**Comment by cubanflyer** [comment]
Hi John


As you can see the core code looks a bit of a mess, that is back from 
Openbravo days, I want to try and tidy that up but need to be careful 
that nothing get broken.

I am going to adopt the black icons by default, but I am also changing 
the way they are handle to allow the user to use their own colour set.

John

**Comment by Hedydd** [comment]
These changes have now been done on a branch off ChromisPOS/ChromisPOS/master and a new pull request generated on that branch. This pull request is now obsolete.

**Pull request closed without merging**
